export const sampleMarkets = [
  {
    market: "Cleveland, OH",
    region: "Midwest",
    price: 125000,
    rent: 1350,
    yield: 13.0,
    score: 88,
    risk: "Moderate",
    vacancy: 6.8,
    renterDemand: "High",
    avgTaxRate: 2.1,
    note: "Strong rent-to-price ratio with a large renter base.",
  },
  {
    market: "Birmingham, AL",
    region: "South",
    price: 145000,
    rent: 1450,
    yield: 12.0,
    score: 84,
    risk: "Moderate",
    vacancy: 7.2,
    renterDemand: "High",
    avgTaxRate: 0.7,
    note: "Good gross yield profile with landlord-friendly dynamics.",
  },
  {
    market: "Memphis, TN",
    region: "South",
    price: 135000,
    rent: 1300,
    yield: 11.6,
    score: 81,
    risk: "Higher",
    vacancy: 8.5,
    renterDemand: "High",
    avgTaxRate: 1.2,
    note: "Strong rental demand, but management and neighborhood selection matter.",
  },
  {
    market: "Peoria, IL",
    region: "Midwest",
    price: 105000,
    rent: 1150,
    yield: 13.1,
    score: 83,
    risk: "Moderate",
    vacancy: 7.8,
    renterDemand: "Medium",
    avgTaxRate: 2.5,
    note: "Low entry price and attractive gross yield.",
  },
  {
    market: "Mobile, AL",
    region: "South",
    price: 155000,
    rent: 1500,
    yield: 11.6,
    score: 79,
    risk: "Moderate",
    vacancy: 7.0,
    renterDemand: "Medium",
    avgTaxRate: 0.6,
    note: "Good yield with coastal insurance diligence needed.",
  },
  {
    market: "Detroit, MI",
    region: "Midwest",
    price: 90000,
    rent: 1500,
    yield: 20.0,
    score: 86,
    risk: "Higher",
    vacancy: 9.2,
    renterDemand: "High",
    avgTaxRate: 1.9,
    note: "Very strong sample gross yield, but block-by-block risk is critical.",
  },
  {
    market: "Indianapolis, IN",
    region: "Midwest",
    price: 175000,
    rent: 1550,
    yield: 10.6,
    score: 76,
    risk: "Moderate",
    vacancy: 6.5,
    renterDemand: "High",
    avgTaxRate: 0.9,
    note: "More stable market with slightly lower gross yield.",
  },
  {
    market: "Kansas City, MO",
    region: "Midwest",
    price: 185000,
    rent: 1600,
    yield: 10.4,
    score: 74,
    risk: "Moderate",
    vacancy: 6.9,
    renterDemand: "Medium",
    avgTaxRate: 1.4,
    note: "Good investor market, but pricing has moved up.",
  },
  {
    market: "Tulsa, OK",
    region: "South",
    price: 165000,
    rent: 1450,
    yield: 10.5,
    score: 73,
    risk: "Moderate",
    vacancy: 7.1,
    renterDemand: "Medium",
    avgTaxRate: 1.0,
    note: "Affordable entry point with steady rental demand.",
  },
  {
    market: "Rochester, NY",
    region: "Northeast",
    price: 155000,
    rent: 1400,
    yield: 10.8,
    score: 75,
    risk: "Moderate",
    vacancy: 6.7,
    renterDemand: "Medium",
    avgTaxRate: 2.7,
    note: "Solid gross yield, but taxes and local rules need review.",
  },
  {
    market: "Buffalo, NY",
    region: "Northeast",
    price: 150000,
    rent: 1425,
    yield: 11.4,
    score: 77,
    risk: "Moderate",
    vacancy: 6.9,
    renterDemand: "Medium",
    avgTaxRate: 2.6,
    note: "Affordable housing stock with decent rental fundamentals.",
  },
  {
    market: "Syracuse, NY",
    region: "Northeast",
    price: 140000,
    rent: 1350,
    yield: 11.6,
    score: 78,
    risk: "Moderate",
    vacancy: 7.0,
    renterDemand: "Medium",
    avgTaxRate: 2.5,
    note: "Good rent-to-price profile with university and healthcare demand drivers.",
  },
  {
    market: "Pittsburgh, PA",
    region: "Northeast",
    price: 170000,
    rent: 1500,
    yield: 10.6,
    score: 76,
    risk: "Moderate",
    vacancy: 6.4,
    renterDemand: "High",
    avgTaxRate: 2.0,
    note: "Stable renter base with healthcare, education, and tech employment anchors.",
  },
  {
    market: "Dayton, OH",
    region: "Midwest",
    price: 130000,
    rent: 1250,
    yield: 11.5,
    score: 78,
    risk: "Moderate",
    vacancy: 7.3,
    renterDemand: "Medium",
    avgTaxRate: 1.8,
    note: "Affordable entry prices and workable rental yield.",
  },
  {
    market: "Cincinnati, OH",
    region: "Midwest",
    price: 180000,
    rent: 1600,
    yield: 10.7,
    score: 75,
    risk: "Moderate",
    vacancy: 6.6,
    renterDemand: "High",
    avgTaxRate: 1.7,
    note: "Larger metro with steady rental demand, though pricing is less discounted.",
  },
  {
    market: "Toledo, OH",
    region: "Midwest",
    price: 115000,
    rent: 1200,
    yield: 12.5,
    score: 80,
    risk: "Moderate",
    vacancy: 7.9,
    renterDemand: "Medium",
    avgTaxRate: 2.1,
    note: "Low purchase prices can produce attractive paper yield.",
  },
  {
    market: "Akron, OH",
    region: "Midwest",
    price: 120000,
    rent: 1225,
    yield: 12.3,
    score: 79,
    risk: "Moderate",
    vacancy: 7.6,
    renterDemand: "Medium",
    avgTaxRate: 1.9,
    note: "Affordable market with potential for strong rent-to-price ratios.",
  },
  {
    market: "Youngstown, OH",
    region: "Midwest",
    price: 85000,
    rent: 1000,
    yield: 14.1,
    score: 74,
    risk: "Higher",
    vacancy: 9.5,
    renterDemand: "Medium",
    avgTaxRate: 1.8,
    note: "High yield potential, but vacancy, resale, and property condition risk matter.",
  },
  {
    market: "Milwaukee, WI",
    region: "Midwest",
    price: 170000,
    rent: 1500,
    yield: 10.6,
    score: 74,
    risk: "Moderate",
    vacancy: 6.8,
    renterDemand: "High",
    avgTaxRate: 2.2,
    note: "Larger Midwest market with good renter demand and moderate yields.",
  },
  {
    market: "St. Louis, MO",
    region: "Midwest",
    price: 140000,
    rent: 1350,
    yield: 11.6,
    score: 77,
    risk: "Moderate",
    vacancy: 7.5,
    renterDemand: "High",
    avgTaxRate: 1.4,
    note: "Strong investor activity with neighborhood-level underwriting required.",
  },
  {
    market: "Little Rock, AR",
    region: "South",
    price: 155000,
    rent: 1400,
    yield: 10.8,
    score: 73,
    risk: "Moderate",
    vacancy: 7.4,
    renterDemand: "Medium",
    avgTaxRate: 0.8,
    note: "Affordable Southern market with reasonable rental demand.",
  },
  {
    market: "Oklahoma City, OK",
    region: "South",
    price: 175000,
    rent: 1500,
    yield: 10.3,
    score: 72,
    risk: "Moderate",
    vacancy: 7.0,
    renterDemand: "Medium",
    avgTaxRate: 1.0,
    note: "Steady market, but yields may be thinner than smaller cities.",
  },
  {
    market: "Louisville, KY",
    region: "South",
    price: 180000,
    rent: 1550,
    yield: 10.3,
    score: 72,
    risk: "Moderate",
    vacancy: 6.8,
    renterDemand: "Medium",
    avgTaxRate: 1.0,
    note: "Stable rental demand with moderate affordability.",
  },
  {
    market: "Shreveport, LA",
    region: "South",
    price: 125000,
    rent: 1250,
    yield: 12.0,
    score: 73,
    risk: "Higher",
    vacancy: 8.7,
    renterDemand: "Medium",
    avgTaxRate: 0.9,
    note: "Attractive rent-to-price ratio, but market and property risk need diligence.",
  },
  {
    market: "Jackson, MS",
    region: "South",
    price: 110000,
    rent: 1200,
    yield: 13.1,
    score: 72,
    risk: "Higher",
    vacancy: 9.1,
    renterDemand: "Medium",
    avgTaxRate: 0.9,
    note: "High gross yield potential with infrastructure and vacancy diligence needed.",
  },
  {
    market: "Fort Wayne, IN",
    region: "Midwest",
    price: 165000,
    rent: 1450,
    yield: 10.5,
    score: 74,
    risk: "Moderate",
    vacancy: 6.5,
    renterDemand: "Medium",
    avgTaxRate: 0.9,
    note: "More stable Midwest market with moderate rent-to-price potential.",
  },
  {
    market: "Evansville, IN",
    region: "Midwest",
    price: 130000,
    rent: 1225,
    yield: 11.3,
    score: 73,
    risk: "Moderate",
    vacancy: 7.4,
    renterDemand: "Medium",
    avgTaxRate: 0.9,
    note: "Low entry price and workable rent-to-price ratio.",
  },
  {
    market: "Wichita, KS",
    region: "Midwest",
    price: 155000,
    rent: 1350,
    yield: 10.5,
    score: 72,
    risk: "Moderate",
    vacancy: 7.2,
    renterDemand: "Medium",
    avgTaxRate: 1.3,
    note: "Affordable market with steady rental demand.",
  },
  {
    market: "Des Moines, IA",
    region: "Midwest",
    price: 190000,
    rent: 1600,
    yield: 10.1,
    score: 71,
    risk: "Moderate",
    vacancy: 5.9,
    renterDemand: "Medium",
    avgTaxRate: 1.5,
    note: "More stable market, though affordability is less compelling.",
  },
  {
    market: "Grand Rapids, MI",
    region: "Midwest",
    price: 210000,
    rent: 1700,
    yield: 9.7,
    score: 70,
    risk: "Moderate",
    vacancy: 5.8,
    renterDemand: "High",
    avgTaxRate: 1.6,
    note: "Stronger market quality but weaker pure gross yield profile.",
  },
  {
    market: "Lansing, MI",
    region: "Midwest",
    price: 150000,
    rent: 1350,
    yield: 10.8,
    score: 73,
    risk: "Moderate",
    vacancy: 7.0,
    renterDemand: "Medium",
    avgTaxRate: 1.8,
    note: "Affordable pricing with university and government demand anchors.",
  },
  {
    market: "Flint, MI",
    region: "Midwest",
    price: 75000,
    rent: 950,
    yield: 15.2,
    score: 70,
    risk: "Higher",
    vacancy: 10.2,
    renterDemand: "Medium",
    avgTaxRate: 1.8,
    note: "Very high paper yield, but high-risk underwriting is required.",
  },
  {
    market: "Huntsville, AL",
    region: "South",
    price: 240000,
    rent: 1850,
    yield: 9.3,
    score: 70,
    risk: "Moderate",
    vacancy: 5.6,
    renterDemand: "High",
    avgTaxRate: 0.7,
    note: "Strong economic fundamentals, but pricing can reduce gross yield.",
  },
  {
    market: "Montgomery, AL",
    region: "South",
    price: 135000,
    rent: 1300,
    yield: 11.6,
    score: 75,
    risk: "Moderate",
    vacancy: 7.8,
    renterDemand: "Medium",
    avgTaxRate: 0.7,
    note: "Lower entry prices and solid rent-to-price ratio.",
  },
  {
    market: "Columbus, GA",
    region: "South",
    price: 150000,
    rent: 1400,
    yield: 11.2,
    score: 74,
    risk: "Moderate",
    vacancy: 7.4,
    renterDemand: "Medium",
    avgTaxRate: 0.9,
    note: "Affordable market with military and local employment demand drivers.",
  },
  {
    market: "Augusta, GA",
    region: "South",
    price: 165000,
    rent: 1450,
    yield: 10.5,
    score: 72,
    risk: "Moderate",
    vacancy: 7.1,
    renterDemand: "Medium",
    avgTaxRate: 0.9,
    note: "Steady renter base with moderate yield potential.",
  },
  {
    market: "Greensboro, NC",
    region: "South",
    price: 210000,
    rent: 1650,
    yield: 9.4,
    score: 69,
    risk: "Moderate",
    vacancy: 6.2,
    renterDemand: "High",
    avgTaxRate: 0.9,
    note: "Better market quality but thinner gross yield math.",
  },
  {
    market: "Winston-Salem, NC",
    region: "South",
    price: 195000,
    rent: 1550,
    yield: 9.5,
    score: 69,
    risk: "Moderate",
    vacancy: 6.3,
    renterDemand: "Medium",
    avgTaxRate: 0.9,
    note: "Reasonable demand, but pricing may limit high-yield deals.",
  },
  {
    market: "Columbia, SC",
    region: "South",
    price: 180000,
    rent: 1550,
    yield: 10.3,
    score: 72,
    risk: "Moderate",
    vacancy: 6.9,
    renterDemand: "Medium",
    avgTaxRate: 0.8,
    note: "Affordable Southern market with student, military, and government demand.",
  },
  {
    market: "Spartanburg, SC",
    region: "South",
    price: 175000,
    rent: 1500,
    yield: 10.3,
    score: 71,
    risk: "Moderate",
    vacancy: 6.8,
    renterDemand: "Medium",
    avgTaxRate: 0.8,
    note: "Growing secondary market with moderate rental yield.",
  },
];

export const sampleProperties = [
  {
    address: "1248 Maple Ave",
    market: "Cleveland, OH",
    type: "Single-family",
    price: 132000,
    rent: 1450,
    beds: 3,
    baths: 1,
    score: 87,
    yield: 13.2,
    avgTaxRate: 2.1,
    status: "New today",
  },
  {
    address: "782 Oak Ridge Dr",
    market: "Birmingham, AL",
    type: "Single-family",
    price: 149000,
    rent: 1550,
    beds: 3,
    baths: 2,
    score: 84,
    yield: 12.5,
    avgTaxRate: 0.7,
    status: "2 days old",
  },
  {
    address: "3316 Poplar St",
    market: "Memphis, TN",
    type: "Duplex",
    price: 168000,
    rent: 1850,
    beds: 4,
    baths: 2,
    score: 82,
    yield: 13.2,
    avgTaxRate: 1.2,
    status: "New today",
  },
  {
    address: "210 W Adams St",
    market: "Peoria, IL",
    type: "Single-family",
    price: 99000,
    rent: 1125,
    beds: 2,
    baths: 1,
    score: 81,
    yield: 13.6,
    avgTaxRate: 2.5,
    status: "4 days old",
  },
  {
    address: "919 Bayview Ln",
    market: "Mobile, AL",
    type: "Single-family",
    price: 158000,
    rent: 1500,
    beds: 3,
    baths: 2,
    score: 76,
    yield: 11.4,
    avgTaxRate: 0.6,
    status: "6 days old",
  },
  {
    address: "4472 Grand Blvd",
    market: "Detroit, MI",
    type: "Single-family",
    price: 90000,
    rent: 1500,
    beds: 3,
    baths: 1,
    score: 86,
    yield: 20.0,
    avgTaxRate: 1.9,
    status: "1 day old",
  },
  {
    address: "6502 E 12th St",
    market: "Indianapolis, IN",
    type: "Single-family",
    price: 174000,
    rent: 1575,
    beds: 3,
    baths: 2,
    score: 73,
    yield: 10.9,
    avgTaxRate: 0.9,
    status: "3 days old",
  },
];
