export const sampleListings = [
  {
    id: "chicago-south-shore-001",
    address: "Sample South Shore 3-flat",
    market: "Chicago Area",
    submarket: "South Shore",
    propertyType: "Multi unit",
    price: 285000,
    beds: 5,
    baths: 3,
    estimatedGrossMonthlyRent: 3900,
    grossYield: 16.4,
    avgTaxRate: 2.1,
    buyToRentScore: 88,
    status: "For sale",
    listingUrl: "#",
  },
  {
    id: "chicago-south-shore-002",
    address: "Sample South Shore single-family",
    market: "Chicago Area",
    submarket: "South Shore",
    propertyType: "House",
    price: 185000,
    beds: 3,
    baths: 2,
    estimatedGrossMonthlyRent: 2200,
    grossYield: 14.3,
    avgTaxRate: 2.1,
    buyToRentScore: 84,
    status: "For sale",
    listingUrl: "#",
  },
  {
    id: "chicago-austin-001",
    address: "Sample Austin duplex",
    market: "Chicago Area",
    submarket: "Austin",
    propertyType: "Multi unit",
    price: 230000,
    beds: 4,
    baths: 2,
    estimatedGrossMonthlyRent: 3100,
    grossYield: 16.2,
    avgTaxRate: 2.2,
    buyToRentScore: 86,
    status: "For sale",
    listingUrl: "#",
  },
  {
    id: "chicago-cicero-001",
    address: "Sample Cicero house",
    market: "Chicago Area",
    submarket: "Cicero",
    propertyType: "House",
    price: 225000,
    beds: 3,
    baths: 2,
    estimatedGrossMonthlyRent: 2300,
    grossYield: 12.3,
    avgTaxRate: 2.1,
    buyToRentScore: 80,
    status: "For sale",
    listingUrl: "#",
  },
  {
    id: "chicago-berwyn-001",
    address: "Sample Berwyn bungalow",
    market: "Chicago Area",
    submarket: "Berwyn",
    propertyType: "House",
    price: 285000,
    beds: 3,
    baths: 2,
    estimatedGrossMonthlyRent: 2450,
    grossYield: 10.3,
    avgTaxRate: 2.0,
    buyToRentScore: 78,
    status: "For sale",
    listingUrl: "#",
  },
  {
    id: "chicago-calumet-001",
    address: "Sample Calumet City rental",
    market: "Chicago Area",
    submarket: "Calumet City",
    propertyType: "House",
    price: 145000,
    beds: 3,
    baths: 1,
    estimatedGrossMonthlyRent: 1650,
    grossYield: 13.7,
    avgTaxRate: 2.3,
    buyToRentScore: 79,
    status: "For sale",
    listingUrl: "#",
  },
  {
    id: "detroit-001",
    address: "Sample East Detroit rental",
    market: "Detroit Area",
    submarket: "East Detroit",
    propertyType: "House",
    price: 90000,
    beds: 3,
    baths: 1,
    estimatedGrossMonthlyRent: 1500,
    grossYield: 20.0,
    avgTaxRate: 1.9,
    buyToRentScore: 86,
    status: "For sale",
    listingUrl: "#",
  },
  {
    id: "detroit-002",
    address: "Sample Detroit duplex",
    market: "Detroit Area",
    submarket: "East Detroit",
    propertyType: "Multi unit",
    price: 135000,
    beds: 4,
    baths: 2,
    estimatedGrossMonthlyRent: 2400,
    grossYield: 21.3,
    avgTaxRate: 1.9,
    buyToRentScore: 89,
    status: "For sale",
    listingUrl: "#",
  },
  {
    id: "cleveland-001",
    address: "Sample Old Brooklyn duplex",
    market: "Cleveland Area",
    submarket: "Old Brooklyn",
    propertyType: "Multi unit",
    price: 165000,
    beds: 4,
    baths: 2,
    estimatedGrossMonthlyRent: 2300,
    grossYield: 16.7,
    avgTaxRate: 2.1,
    buyToRentScore: 87,
    status: "For sale",
    listingUrl: "#",
  },
  {
    id: "birmingham-001",
    address: "Sample Ensley rental",
    market: "Birmingham Area",
    submarket: "Ensley",
    propertyType: "House",
    price: 125000,
    beds: 3,
    baths: 1,
    estimatedGrossMonthlyRent: 1350,
    grossYield: 13.0,
    avgTaxRate: 0.7,
    buyToRentScore: 80,
    status: "For sale",
    listingUrl: "#",
  },
];
