export const sampleSubmarkets = [
  {
    id: "chicago-south-shore",
    parentMarket: "Chicago Area",
    submarket: "South Shore",
    state: "IL",
    propertyTypes: ["House", "Multi unit", "Apartment building"],
    bedrooms: [2, 3, 4, 5],
    bathrooms: [1, 2, 3],
    priceMin: 125000,
    priceMax: 350000,
    medianHomePrice: 215000,
    grossMonthlyRent: 2200,
    grossYield: 12.3,
    avgTaxRate: 2.1,
    listingCount: 38,
    listingCountLtm: 148,
    locationScore: 76,
    propertyRatingScore: 82,
    rentalRevenuePotential: 85,
    buyToRentScore: 84,
    renterDemand: "High",
    marketRisk: "Moderate",
    latitude: 41.758,
    longitude: -87.575,
    note: "Strong rent-to-price fundamentals with good access to the city and lakefront neighborhoods.",
  },
  {
    id: "chicago-bronzeville",
    parentMarket: "Chicago Area",
    submarket: "Bronzeville",
    state: "IL",
    propertyTypes: ["Condo", "Townhome", "Multi unit", "Apartment building"],
    bedrooms: [1, 2, 3, 4],
    bathrooms: [1, 2, 3],
    priceMin: 175000,
    priceMax: 500000,
    medianHomePrice: 310000,
    grossMonthlyRent: 2600,
    grossYield: 10.1,
    avgTaxRate: 2.0,
    listingCount: 26,
    listingCountLtm: 115,
    locationScore: 82,
    propertyRatingScore: 80,
    rentalRevenuePotential: 84,
    buyToRentScore: 81,
    renterDemand: "High",
    marketRisk: "Moderate",
    latitude: 41.824,
    longitude: -87.625,
    note: "Higher price point but strong renter demand and improving neighborhood fundamentals.",
  },
  {
    id: "chicago-austin",
    parentMarket: "Chicago Area",
    submarket: "Austin",
    state: "IL",
    propertyTypes: ["House", "Multi unit"],
    bedrooms: [2, 3, 4, 5],
    bathrooms: [1, 2, 3],
    priceMin: 90000,
    priceMax: 300000,
    medianHomePrice: 175000,
    grossMonthlyRent: 1900,
    grossYield: 13.0,
    avgTaxRate: 2.2,
    listingCount: 44,
    listingCountLtm: 190,
    locationScore: 68,
    propertyRatingScore: 78,
    rentalRevenuePotential: 82,
    buyToRentScore: 79,
    renterDemand: "High",
    marketRisk: "Higher",
    latitude: 41.887,
    longitude: -87.764,
    note: "Affordable pricing and strong rent potential, but property condition and block-level risk matter.",
  },
  {
    id: "chicago-cicero",
    parentMarket: "Chicago Area",
    submarket: "Cicero",
    state: "IL",
    propertyTypes: ["House", "Townhome", "Multi unit"],
    bedrooms: [2, 3, 4],
    bathrooms: [1, 2],
    priceMin: 160000,
    priceMax: 375000,
    medianHomePrice: 245000,
    grossMonthlyRent: 2300,
    grossYield: 11.3,
    avgTaxRate: 2.1,
    listingCount: 31,
    listingCountLtm: 132,
    locationScore: 74,
    propertyRatingScore: 80,
    rentalRevenuePotential: 81,
    buyToRentScore: 80,
    renterDemand: "Medium",
    marketRisk: "Moderate",
    latitude: 41.845,
    longitude: -87.753,
    note: "Good affordability near Chicago with steady rental demand.",
  },
  {
    id: "chicago-berwyn",
    parentMarket: "Chicago Area",
    submarket: "Berwyn",
    state: "IL",
    propertyTypes: ["House", "Townhome", "Multi unit"],
    bedrooms: [2, 3, 4],
    bathrooms: [1, 2, 3],
    priceMin: 190000,
    priceMax: 425000,
    medianHomePrice: 285000,
    grossMonthlyRent: 2450,
    grossYield: 10.3,
    avgTaxRate: 2.0,
    listingCount: 23,
    listingCountLtm: 104,
    locationScore: 79,
    propertyRatingScore: 81,
    rentalRevenuePotential: 79,
    buyToRentScore: 78,
    renterDemand: "Medium",
    marketRisk: "Moderate",
    latitude: 41.85,
    longitude: -87.794,
    note: "Stable suburb with moderate yield and stronger neighborhood quality.",
  },
  {
    id: "chicago-calumet-city",
    parentMarket: "Chicago Area",
    submarket: "Calumet City",
    state: "IL",
    propertyTypes: ["House", "Townhome", "Multi unit"],
    bedrooms: [2, 3, 4],
    bathrooms: [1, 2],
    priceMin: 95000,
    priceMax: 260000,
    medianHomePrice: 155000,
    grossMonthlyRent: 1650,
    grossYield: 12.8,
    avgTaxRate: 2.3,
    listingCount: 29,
    listingCountLtm: 121,
    locationScore: 66,
    propertyRatingScore: 76,
    rentalRevenuePotential: 78,
    buyToRentScore: 77,
    renterDemand: "Medium",
    marketRisk: "Higher",
    latitude: 41.615,
    longitude: -87.529,
    note: "Low entry prices and workable gross yield with higher local diligence needed.",
  },
  {
    id: "detroit-east-side",
    parentMarket: "Detroit Area",
    submarket: "East Detroit",
    state: "MI",
    propertyTypes: ["House", "Multi unit"],
    bedrooms: [2, 3, 4],
    bathrooms: [1, 2],
    priceMin: 55000,
    priceMax: 160000,
    medianHomePrice: 90000,
    grossMonthlyRent: 1500,
    grossYield: 20.0,
    avgTaxRate: 1.9,
    listingCount: 52,
    listingCountLtm: 240,
    locationScore: 62,
    propertyRatingScore: 80,
    rentalRevenuePotential: 88,
    buyToRentScore: 86,
    renterDemand: "High",
    marketRisk: "Higher",
    latitude: 42.409,
    longitude: -82.946,
    note: "Very strong sample gross yield, but block-by-block risk is critical.",
  },
  {
    id: "cleveland-old-brooklyn",
    parentMarket: "Cleveland Area",
    submarket: "Old Brooklyn",
    state: "OH",
    propertyTypes: ["House", "Duplex", "Multi unit"],
    bedrooms: [2, 3, 4],
    bathrooms: [1, 2],
    priceMin: 95000,
    priceMax: 225000,
    medianHomePrice: 145000,
    grossMonthlyRent: 1550,
    grossYield: 12.8,
    avgTaxRate: 2.1,
    listingCount: 34,
    listingCountLtm: 156,
    locationScore: 75,
    propertyRatingScore: 82,
    rentalRevenuePotential: 83,
    buyToRentScore: 84,
    renterDemand: "High",
    marketRisk: "Moderate",
    latitude: 41.432,
    longitude: -81.704,
    note: "Affordable housing stock with attractive rent-to-price fundamentals.",
  },
  {
    id: "birmingham-ensley",
    parentMarket: "Birmingham Area",
    submarket: "Ensley",
    state: "AL",
    propertyTypes: ["House", "Multi unit"],
    bedrooms: [2, 3, 4],
    bathrooms: [1, 2],
    priceMin: 70000,
    priceMax: 180000,
    medianHomePrice: 125000,
    grossMonthlyRent: 1350,
    grossYield: 13.0,
    avgTaxRate: 0.7,
    listingCount: 27,
    listingCountLtm: 111,
    locationScore: 67,
    propertyRatingScore: 78,
    rentalRevenuePotential: 81,
    buyToRentScore: 80,
    renterDemand: "Medium",
    marketRisk: "Moderate",
    latitude: 33.498,
    longitude: -86.89,
    note: "Low taxes and affordable pricing can create strong gross yield potential.",
  },
];
